name: streetpizza
favicon: null
layout_spectrum: 0.4253654850181192
typography_spectrum: 0.9538412468973547
title: Kevin Middleton
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-644883-4
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.4806061072740704
  rhythmicContrast: 0.5
purpose: []
