name: Kevin Middleton
favicon: null
layout_spectrum: 0.8853046
typography_spectrum: 0.6290323
title: Kevin Middleton
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-644883-4
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c2c2c2'
    - '#002577'
    - '#8e9900'
    - '#c91e1f'
    - '#4e0014'
  brandStrength: 0.25
  lightness: 0.75
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
